#!/usr/bin/env bash
if [ "$#" -lt 1 ]
then
  echo "Usage: ./vmstart vm_name"
  echo
  echo "Starts a VM that is already created."
  exit 1
fi

trap popd EXIT
pushd $PWD
cd $(dirname "$0")

username="$(head -n1 creds/default.txt)"
rest_args=("${all_args[@]:2}")
zone="$(gcloud compute instances list | awk -v vm=$1 '{ if($1 == vm) {print $2} }')"
gcloud compute instances start $1 --zone=$zone ${rest_args[@]}
