#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

echo ">>> Running pylint on your changed python files -- please wait..."

git diff --cached --name-only --diff-filter=ACM | xargs pylint --rcfile=.pylint$
exit 0
